# Generated by Django 4.0.4 on 2022-04-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('quantity', models.PositiveIntegerField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('genre', models.CharField(choices=[('Comedy', 'COMEDY'), ('Action', 'ACTION'), ('Romantic', 'ROMANTIC'), ('Horror', 'HORROR'), ('Anime', 'ANIME'), ('Fantastic', 'FANTASTIC')], max_length=100)),
            ],
        ),
    ]
