# Generated by Django 4.0.4 on 2022-04-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_showcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='duration',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
